version: "3.3"
services:
  app:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
